#!/ffp/bin/sh
# ----------------------------------------------
# Retrieve dns-325 fan status
#
# Used by http://bernaerts.dyndns.org/nas/314-dns325-ffp7-snmp-supervise-temperature-case-hdd
#
# Parameters : none
#
# 30/06/2014, V1.0 - Creation by N. Bernaerts 
# 02/07/2014, V1.1 - Deal with switch to auto mode
# 14/07/2014, V1.2 - Change fan speed to 0..2
# ----------------------------------------------

# define display value for 3 states (stop, low & high)
LEVEL_STOP="0"
LEVEL_LOW="1"
LEVEL_HIGH="2"

# retrieve fan status from fanspeed command
FAN_SPEED=`fanspeed g`

# if fan is not rotating
if [ "$FAN_SPEED" = "stop" ]
then
  # display stop level
  echo $LEVEL_STOP

# fan is supposed to rotate, get value from user.log
else
  # retrieve last fan speed change in /var/log/user.log
  LOG_SPEED=`cat /var/log/user.log | grep "Set Fan Speed" | tail -n 1 | sed 's/^.*"\([^"]*\)".*$/\1/g' | tr '[:upper:]' '[:lower:]'`

  # return the value
  echo $LOG_SPEED
fi
