#!/ffp/bin/sh
# ----------------------------------------------
# Retrieve dns-325 fan status
#
# Used by http://bernaerts.dyndns.org/nas/314-dns325-ffp7-snmp-supervise-temperature-case-hdd
#
# Parameters : none
#
# 30/06/2014, V1.0 - Creation by N. Bernaerts 
# 02/07/2014, V1.1 - Deal with switch to auto mode
# ----------------------------------------------

# define display value for 3 states (stop, low & high)
LEVEL_STOP="20"
LEVEL_LOW="22"
LEVEL_HIGH="24"

# retrieve fan status from fanspeed command
FAN_SPEED=`fanspeed g`

# if fan is not rotating
if [ "$FAN_SPEED" = "stop" ]
then
  # display stop level
  echo $LEVEL_STOP

# fan is supposed to rotate, get value from user.log
else
  # retrieve last fan speed change in /var/log/user.log
  LOG_SPEED=`cat /var/log/user.log | grep "Set Fan Speed" | tail -n 1 | sed 's/^.*"\([^"]*\)".*$/\1/g' | tr '[:upper:]' '[:lower:]'`

  # convert literal state to numerical value (off=20, low=22, high=24)
  case $LOG_SPEED in
    high) echo $LEVEL_HIGH ;;
    low)  echo $LEVEL_LOW  ;;
    *)    echo $LEVEL_STOP ;;
  esac
fi
