#!/ffp/bin/bash
# ---------------------------------------------------
#  /ffp/sbin/dashbutton
#
#  Infinite loop to detect a dash button activation
#   and trigger an action script
#
#  Revision history :
#    20/01/2017, V1.0 - Creation
#    04/03/2017, V1.1 - Add parameters and MAC address detection
#    14/12/2017, V1.2 - Use tcpdump to detect button
# ---------------------------------------------------

# if no argument, display help
if [ $# -eq 0 ] 
then
  echo "Tool to detect a dash button press and trigger an associated action."
  echo "One of these 2 parameters is compulsory :"
  echo "  --mac-address <mac-address>       MAC address of dash button"
  echo "  --ip-address <ip-address>         IP address of dash button"
  echo "Other parameters are :"
  echo "  --net-interface <name>            Name of local network interface"
  echo "  --action <script-name>            Script to run when dash button detected (compulsory)"
  exit
fi

# loop to retrieve arguments
while test $# -gt 0
do
  case "$1" in
    "--mac-address") shift; MAC_ADDRESS="$1"; shift; ;;
    "--ip-address") shift; IP_ADDRESS="$1"; shift; ;;
    "--net-interface") shift; NET_INTERFACE="$1"; shift; ;;
    "--action") shift; SCRIPT_ACTION="$1"; shift; ;;
    *) shift; ;;
  esac
done

# check tools
command -v tcpdump >/dev/null 2>&1 || { echo "tcpdump not installed. please run # slacker -a tcpdump"; exit 1; }

# test parameters
[ "${MAC_ADDRESS}" = "" -a "${IP_ADDRESS}" = "" ] && { echo "You should provide either MAC address (--mac-adddress) or IP address (--ip-address) of dash button"; exit 1; }
[ "${SCRIPT_ACTION}" = "" ] && { echo "You should provide a script to run (--action) when dash button is pressed"; exit 1; }

# set PATH
PATH="/ffp/sbin:/usr/sbin:/ffp/bin:/usr/bin:/bin"

# generate tcpdump command parameters
ARR_PARAM=("-c" "1")
[ "${NET_INTERFACE}" != "" ]  && ARR_PARAM=("${ARR_PARAM[@]}" "-i" "${NET_INTERFACE}")
[ "${MAC_ADDRESS}" != "" ]  && ARR_PARAM=("${ARR_PARAM[@]}" "ether" "host" "${MAC_ADDRESS}") || ARR_PARAM=("${ARR_PARAM[@]}" "host" "${IP_ADDRESS}}")

# loop to detect dash button
while true
do
  # detect button on LAN
  tcpdump "${ARR_PARAM[@]}"

  # display detection
  echo "Dash button detected"

  # run action script
  ${SCRIPT_ACTION}

  # wait for 15s
  sleep 15
done
