#!/ffp/bin/bash

# ---------------------
#   Quote of the day
# ---------------------

TITLE="Pensée du soir"

# get quote of the day
wget --quiet -O - http://www.mon-poeme.fr/citation-du-jour/ | sed -n '/<q>/,$p' | sed '/div>/q' > /tmp/quote.html

# extract quote and author
QUOTE=$(cat /tmp/quote.html | head -n 1 | sed "s/^.*<q>\(.*\)<\/q>.*$/\1/")
AUTHOR=$(cat /tmp/quote.html | grep "Citation" | head -n 1 | sed "s/^.*Citation de \(.*\)<\/p>.*$/\1/" | sed "s/<[^>]*>//g" | sed "s/ ;/,/g")

# send quote
telegram-notify --title "${TITLE}" --text "${QUOTE}\n\n_${AUTHOR}_"

# ---------------------
#  Good night message
# ---------------------

TITLE="Bonne nuit ..."
TEXT="Je suis couché.\nA demain.\n\n_Papa_"

# send message
telegram-notify --title "${TITLE}" --text "${TEXT}"
